// Central registry of source & layer ids used for WorldEye overlays.
export const SRC = {
  activity: 'we-activity',
  graticule: 'we-graticule',
  draw: 'we-draw',
  drawDraft: 'we-draw-draft',
  measure: 'we-measure',
  aircraft: 'we-aircraft',
  aircraftTrail: 'we-aircraft-trail',
  ships: 'we-ships',
  shipsTrail: 'we-ships-trail',
  trains: 'we-trains',
  trainsTrail: 'we-trains-trail',
  trainsRoute: 'we-trains-route',
  trainsRouteStops: 'we-trains-route-stops',
  fleet: 'we-fleet',
  fleetTrail: 'we-fleet-trail',
  geofences: 'we-geofences',
  trafficIncidents: 'we-traffic-incidents',
  trafficFlow: 'we-traffic-flow',
  cyberThreats: 'we-cyber-threats',
  domainInfra: 'we-domain-infra',
  domainInfraLinks: 'we-domain-infra-links',
  weather: 'we-weather',
  weatherGrid: 'we-weather-grid',
  cyclones: 'we-cyclones',
  wildfires: 'we-wildfires',
  earthquakes: 'we-earthquakes',
  satellites: 'we-satellites',
  satOrbit: 'we-sat-orbit',
  news: 'we-news',
  social: 'we-social',
  alertZones: 'we-alert-zones',
  alertEvents: 'we-alert-events',
} as const

export const LYR = {
  heatmap: 'we-activity-heatmap',
  points: 'we-activity-points',
  graticule: 'we-graticule-lines',
  drawFill: 'we-draw-fill',
  drawLine: 'we-draw-line',
  drawPoint: 'we-draw-point',
  draftFill: 'we-draw-draft-fill',
  draftLine: 'we-draw-draft-line',
  draftPoint: 'we-draw-draft-point',
  measureLine: 'we-measure-line',
  measurePoint: 'we-measure-point',
  weatherRaster: 'we-weather-raster',
  aircraftTrail: 'we-aircraft-trail-line',
  aircraftHalo: 'we-aircraft-halo',
  aircraftIcon: 'we-aircraft-icon',
  aircraftLabel: 'we-aircraft-label',
  shipsTrail: 'we-ships-trail-line',
  shipsHalo: 'we-ships-halo',
  shipsIcon: 'we-ships-icon',
  trainsRouteLine: 'we-trains-route-line',
  trainsRouteStop: 'we-trains-route-stop',
  trainsTrail: 'we-trains-trail-line',
  trainsHalo: 'we-trains-halo',
  trainsIcon: 'we-trains-icon',
  geofenceFill: 'we-geofence-fill',
  geofenceLine: 'we-geofence-line',
  fleetTrail: 'we-fleet-trail-line',
  fleetHalo: 'we-fleet-halo',
  fleetIcon: 'we-fleet-icon',
  trafficHeatmap: 'we-traffic-heatmap',
  trafficFlow: 'we-traffic-flow-pts',
  trafficIncidents: 'we-traffic-incidents-pts',
  cyberThreatsGlow: 'we-cyber-threats-glow',
  cyberThreats: 'we-cyber-threats-pts',
  domainInfraLinks: 'we-domain-infra-links-line',
  domainInfraGlow: 'we-domain-infra-glow',
  domainInfra: 'we-domain-infra-pts',
  domainInfraLabel: 'we-domain-infra-label',
  weatherTemp: 'we-weather-temp',
  weatherWind: 'we-weather-wind',
  weatherLightning: 'we-weather-lightning',
  cyclonesGlow: 'we-cyclones-glow',
  cyclones: 'we-cyclones-pts',
  wildfiresGlow: 'we-wildfires-glow',
  wildfires: 'we-wildfires-pts',
  earthquakesGlow: 'we-earthquakes-glow',
  earthquakes: 'we-earthquakes-pts',
  satOrbit: 'we-sat-orbit-line',
  satActive: 'we-sat-active',
  satStarlink: 'we-sat-starlink',
  satDebris: 'we-sat-debris',
  satLaunches: 'we-sat-launches',
  satIss: 'we-sat-iss',
  satSelected: 'we-sat-selected',
  newsGlow: 'we-news-glow',
  newsPoints: 'we-news-pts',
  socialGlow: 'we-social-glow',
  socialPoints: 'we-social-pts',
  alertZoneFill: 'we-alert-zone-fill',
  alertZoneLine: 'we-alert-zone-line',
  alertEventsGlow: 'we-alert-events-glow',
  alertEvents: 'we-alert-events-pts',
} as const

export const PLANE_IMAGE = 'we-plane'
export const SHIP_IMAGE = 'we-ship'
export const TRAIN_IMAGE = 'we-train'
export const VEHICLE_IMAGE = 'we-vehicle'
export const WIND_IMAGE = 'we-wind-arrow'
