import type { LayerState } from '../types'

export const DEFAULT_LAYERS: LayerState[] = [
  {
    id: 'aircraft',
    name: 'Aircraft (live)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#ffffff',
    description: 'Live flights — click a plane for details',
  },
  {
    id: 'ships',
    name: 'Ships (live AIS)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#38bdf8',
    description: 'Live vessels — click a ship for details',
  },
  {
    id: 'trains',
    name: 'Trains (live)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#34d399',
    description: 'Live trains — click for route, schedule & delays',
  },
  {
    id: 'fleet',
    name: 'Fleet (authorized)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#22c55e',
    description: 'Your authorized fleet devices — click for telematics',
  },
  {
    id: 'geofences',
    name: 'Geofences',
    group: 'Reference',
    visible: true,
    opacity: 0.7,
    color: '#818cf8',
    description: 'Fleet operating zones & restricted areas',
  },
  {
    id: 'traffic-incidents',
    name: 'Traffic Incidents',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#ef4444',
    description: 'Accidents, roadworks & closures — click for details',
  },
  {
    id: 'traffic-flow',
    name: 'Traffic Flow / Congestion',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#22c55e',
    description: 'Measured speed & congestion (heatmap + sensors)',
  },
  {
    id: 'weather-radar',
    name: 'Weather Radar',
    group: 'Overlays',
    visible: false,
    opacity: 0.7,
    color: '#38bdf8',
    description: 'Precipitation radar (RainViewer, last 2h)',
  },
  {
    id: 'activity-heatmap',
    name: 'Activity Heatmap',
    group: 'Overlays',
    visible: true,
    opacity: 0.85,
    color: '#f43f5e',
    description: 'Density of activity signals across the world',
  },
  {
    id: 'activity-points',
    name: 'Activity Points',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#22d3ee',
    description: 'Individual activity signals (click for details)',
  },
  {
    id: 'drawings',
    name: 'My Drawings',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#818cf8',
    description: 'Shapes created with the drawing tools',
  },
  {
    id: 'graticule',
    name: 'Graticule (Grid)',
    group: 'Reference',
    visible: false,
    opacity: 0.5,
    color: '#64748b',
    description: 'Latitude / longitude reference grid',
  },
]
