import type { LayerState } from '../types'

export const DEFAULT_LAYERS: LayerState[] = [
  {
    id: 'aircraft',
    name: 'Aircraft (live)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#1e293b',
    description: 'Live flights — click a plane for details',
  },
  {
    id: 'ships',
    name: 'Ships (live AIS)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#0ea5e9',
    description: 'Live vessels — click a ship for details',
  },
  {
    id: 'trains',
    name: 'Trains (live)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#10b981',
    description: 'Live trains — click for route, schedule & delays',
  },
  {
    id: 'fleet',
    name: 'Fleet (authorized)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#22c55e',
    description: 'Your authorized fleet devices — click for telematics',
  },
  {
    id: 'geofences',
    name: 'Geofences',
    group: 'Reference',
    visible: true,
    opacity: 0.7,
    color: '#6366f1',
    description: 'Fleet operating zones & restricted areas',
  },
  {
    id: 'traffic-incidents',
    name: 'Traffic Incidents',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#ef4444',
    description: 'Accidents, roadworks & closures — click for details',
  },
  {
    id: 'traffic-flow',
    name: 'Traffic Flow / Congestion',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#22c55e',
    description: 'Measured speed & congestion (heatmap + sensors)',
  },
  {
    id: 'cyber-threats',
    name: 'Cyber Threats',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#f43f5e',
    description: 'Known malicious infrastructure (botnet C2 servers)',
  },
  {
    id: 'domain-infra',
    name: 'Domain Infrastructure',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#8b5cf6',
    description: 'Hosting footprint of a looked-up domain (Domain panel)',
  },
  {
    id: 'weather-radar',
    name: 'Weather Radar',
    group: 'Overlays',
    visible: false,
    opacity: 0.7,
    color: '#0ea5e9',
    description: 'Precipitation radar — rain & snow (RainViewer, last 2h)',
  },
  {
    id: 'weather-temp',
    name: 'Temperature',
    group: 'Overlays',
    visible: false,
    opacity: 0.85,
    color: '#f59e0b',
    description: 'Current air temperature field (Open-Meteo)',
  },
  {
    id: 'weather-wind',
    name: 'Wind',
    group: 'Overlays',
    visible: false,
    opacity: 1,
    color: '#0ea5e9',
    description: 'Surface wind — arrows point downwind, sized by speed',
  },
  {
    id: 'weather-lightning',
    name: 'Lightning / Convective',
    group: 'Overlays',
    visible: false,
    opacity: 1,
    color: '#f59e0b',
    description: 'Thunderstorm-risk cells (high CAPE)',
  },
  {
    id: 'cyclones',
    name: 'Storms & Cyclones',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#a855f7',
    description: 'Active tropical cyclones (NOAA NHC)',
  },
  {
    id: 'wildfires',
    name: 'Wildfires',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#f97316',
    description: 'Active wildfires (NASA EONET)',
  },
  {
    id: 'earthquakes',
    name: 'Earthquakes',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#eab308',
    description: 'Earthquakes in the last 24h (USGS)',
  },
  {
    id: 'sat-iss',
    name: 'ISS & Stations',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#06b6d4',
    description: 'Crewed space stations, live-propagated (CelesTrak)',
  },
  {
    id: 'sat-active',
    name: 'Satellites (notable)',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#334155',
    description: 'Brightest / notable active satellites',
  },
  {
    id: 'sat-starlink',
    name: 'Starlink',
    group: 'Overlays',
    visible: false,
    opacity: 1,
    color: '#3b82f6',
    description: 'Starlink constellation (sampled)',
  },
  {
    id: 'sat-debris',
    name: 'Space Debris',
    group: 'Overlays',
    visible: false,
    opacity: 1,
    color: '#ef4444',
    description: 'Tracked orbital debris (sampled)',
  },
  {
    id: 'sat-launches',
    name: 'Recent Launches',
    group: 'Overlays',
    visible: false,
    opacity: 1,
    color: '#84cc16',
    description: 'Objects launched in the last 30 days',
  },
  {
    id: 'sat-orbits',
    name: 'Orbit Path',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#06b6d4',
    description: 'Ground track of the selected satellite',
  },
  {
    id: 'news-hotspots',
    name: 'News Hotspots',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#f59e0b',
    description: 'Where world news is happening (geoparsed headlines)',
  },
  {
    id: 'social-buzz',
    name: 'Social Buzz',
    group: 'Overlays',
    visible: false,
    opacity: 1,
    color: '#ec4899',
    description: 'Where social conversation is focused (geoparsed posts)',
  },
  {
    id: 'alert-zones',
    name: 'Alert Zones',
    group: 'Reference',
    visible: true,
    opacity: 0.6,
    color: '#f59e0b',
    description: 'Geo-alert areas defined in the Alert Engine',
  },
  {
    id: 'alert-events',
    name: 'Fired Alerts',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#f43f5e',
    description: 'Locations of recently triggered alerts',
  },
  {
    id: 'activity-heatmap',
    name: 'Activity Heatmap',
    group: 'Overlays',
    visible: true,
    opacity: 0.85,
    color: '#f43f5e',
    description: 'Density of activity signals across the world',
  },
  {
    id: 'activity-points',
    name: 'Activity Points',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#06b6d4',
    description: 'Individual activity signals (click for details)',
  },
  {
    id: 'drawings',
    name: 'My Drawings',
    group: 'Overlays',
    visible: true,
    opacity: 1,
    color: '#6366f1',
    description: 'Shapes created with the drawing tools',
  },
  {
    id: 'graticule',
    name: 'Graticule (Grid)',
    group: 'Reference',
    visible: false,
    opacity: 0.5,
    color: '#64748b',
    description: 'Latitude / longitude reference grid',
  },
]
